config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root 'main#index'

  resources :news
  resources :articles
  resources :workers
  resources :services

  post 'comment', to: 'news#comment'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user && user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :dashboard              # grant access to the dashboard
      can :manage, :all
    end

  end
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  desc       :text
#  image      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Article < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  acts_as_taggable
end

app/models/ckeditor/asset.rb
# == Schema Information
#
# Table name: ckeditor_assets
#
#  id                :integer          not null, primary key
#  data_file_name    :string(255)      not null
#  data_content_type :string(255)
#  data_file_size    :integer
#  assetable_id      :integer
#  assetable_type    :string(30)
#  type              :string(30)
#  width             :integer
#  height            :integer
#  created_at        :datetime
#  updated_at        :datetime
#

class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
# == Schema Information
#
# Table name: ckeditor_assets
#
#  id                :integer          not null, primary key
#  data_file_name    :string(255)      not null
#  data_content_type :string(255)
#  data_file_size    :integer
#  assetable_id      :integer
#  assetable_type    :string(30)
#  type              :string(30)
#  width             :integer
#  height            :integer
#  created_at        :datetime
#  updated_at        :datetime
#

class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
# == Schema Information
#
# Table name: ckeditor_assets
#
#  id                :integer          not null, primary key
#  data_file_name    :string(255)      not null
#  data_content_type :string(255)
#  data_file_size    :integer
#  assetable_id      :integer
#  assetable_type    :string(30)
#  type              :string(30)
#  width             :integer
#  height            :integer
#  created_at        :datetime
#  updated_at        :datetime
#

class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  title            :string(50)       default("")
#  comment          :text
#  commentable_id   :integer
#  commentable_type :string(255)
#  user_id          :integer
#  role             :string(255)      default("comments")
#  created_at       :datetime
#  updated_at       :datetime
#

class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment
  validates :comment, presence: :true

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/news.rb
class News < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  acts_as_taggable
  acts_as_commentable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  before_create do

    # Проверка на наличие пользователей.
    # Если ты первый, то удача повернулась к тебе лицом и ты становишься админом!! Та-да!!
      if User.first.nil?
        self.admin = 1
      end

  end

end

app/models/worker.rb
# == Schema Information
#
# Table name: workers
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  role       :string(255)
#  image      :string(255)
#  desc       :text
#  created_at :datetime
#  updated_at :datetime
#

class Worker < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

# Проверка на контроллер, если devise, то вызывает метод configure_permitted_parameters для настройки разрешенных параметров
  before_filter :configure_permitted_parameters, if: :devise_controller?
    
protected

# Параметры, которые принимает гем Devise через пользовательские формы на сайте
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:sign_up) << :email
    devise_parameter_sanitizer.for(:sign_in) << :username
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    if params[:tag]
      @articles = Article.tagged_with(params[:tag]).page(params[:page]).per(3)
    else
      @articles = Article.all.page(params[:page]).per(3)
    end
    @tags = Article.tag_counts
  end

  def show
    @article = Article.find(params[:id])
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
  end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  def index
    if params[:tag]
      @news = News.tagged_with(params[:tag]).page(params[:page]).per(3)
    else
      @news = News.all.page(params[:page]).per(3)
    end
    @tags = News.tag_counts
  end

  def show
    @news = News.find(params[:id])
  end

  def comment
    commentable = News.find(params[:comment][:id])
    comment = commentable.comments.create
    comment.title = params[:comment][:title]
    comment.comment = params[:comment][:comment]
    comment.user_id = params[:comment][:user_id]
    comment.save
    redirect_to :back
  end

  private

    def comment_params
      params.require(:comment).require(:title, :comment)
    end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def index

  end

  def show
    @service = Service.find(params[:id])
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController

  def index
    @workers = Worker.all
  end

  def show
    @worker  = Worker.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/articles/index.slim
- content_for(:page_title, "Статьи")

div.container
  div.row
    div.col-md-10.col-md-offset-1
      div.filter
        - @tags.each do |tag|
          = link_to tag.name, articles_path(tag: tag.name), class: 'btn btn-theme navbar-btn btn-lightblue'
  hr
  - @articles.each do |article|
    div.row
      div.col-md-3
        p.blog-img
          = image_tag article.image, class: 'img-thumbnail'
      div.col-md-9

        article.blog-item
          header
            h2.blog-title.center
              = link_to article_path(article.id) do
                = article.title
            p.blue-box.blog-params.center
              span
                i.fa.fa-calendar
                time datetime="2013-01-12T22:11"
                  = " " + article.updated_at.to_formatted_s(:short) + " "
              span
                i.fa.fa-tags
                - article.tag_list.each do |tag|
                  = link_to " " + tag + " ", articles_path(tag: tag)
              <span class="text-orange">
                i.fa.fa-comments-o
                  |  23 Comments

          p.blog-description
            = article.desc.html_safe
          p.text-right.blog-link-more
            = link_to 'Подробнее', article_path(article.id), class: 'btn btn-theme btn-orange'

  hr

  div.row.center
    div.col-md-12
      = paginate @articles, :theme => 'twitter-bootstrap-3'

app/views/articles/show.slim
div.container
  div.row.center
    div.col-md-12
      = @article.tag_list.inspect

app/views/main/index.html.erb
<%- content_for(:page_title, "«Горловский Городской центр психологической службы»") %>

<div class="container content content-light home-1">
  <section class="row animation-scroll">
    <figure class="col-md-6 animated bounceInLeft" data-animation="bounceInLeft"><img src="img/home1_img1.png" alt=""></figure>
    <article class="col-md-6 animated bounceInRight" data-animation="bounceInRight">
      <h3><strong>Learn</strong> from your <strong>home office</strong></h3>
      <p>We believe that analysis of your company and your customers is key in responding effectively to your promotional needs and we will work with you to fully understand your business.</p>
      <a href="categories.htm" class="link-more">Check out the library <i class="fa fa-arrow-right "></i></a>
    </article>
  </section>

  <section class="row animation-scroll">
    <article class="col-md-6 animated bounceInLeft" data-animation="bounceInLeft">
      <h3><strong>Stay tuned</strong> with your <strong>mobile devices</strong></h3>
      <p>At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur.</p>
      <a href="#" class="link-more">Check out our webapp <i class="fa fa-arrow-right "></i></a>
    </article>
    <figure class="col-md-6 animated bounceInRight" data-animation="bounceInRight"><img src="img/home1_img2.png" alt=""></figure>
  </section>
  <section class="row animation-scroll">
    <figure class="col-md-6 animated bounceInLeft" data-animation="bounceInLeft"><img src="img/home1_img3.png" alt=""></figure>
    <article class="col-md-6 animated bounceInRight" data-animation="bounceInRight">
      <h3><strong>Connect</strong> different file types everywhere</h3>
      <p>We believe that analysis of your company and your customers is key in responding effectively to your promotional needs and we will work with you to fully understand your business.</p>
      <a href="#" class="link-more">Check out the dashboard <i class="fa fa-arrow-right "></i></a>
    </article>
  </section>
  <section class="row animation-scroll">
    <article class="col-md-6 animated" data-animation="bounceInLeft">
      <h3><strong>Share tutorials</strong> with your <strong>friends</strong></h3>
      <p>At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur.</p>
      <a href="#" class="link-more">Go to your portal <i class="fa fa-arrow-right "></i></a>
    </article>
    <div class="col-md-6 animated widget-social" data-animation="bounceInRight">
      <a class="btn btn-social btn-social-circle social-facebook" href="https://www.facebook.com/pages/KL-Webmedia/131260293670757"><i class="fa fa-facebook"></i><span class="click-number">32</span></a>
      <a class="btn btn-social btn-social-circle social-twitter" href="https://twitter.com/KLWebmedia"><i class="fa fa-twitter"></i><span class="click-number">24</span></a>
      <a class="btn btn-social btn-social-circle social-gplus" href="https://plus.google.com/113174627408639682462/posts"><i class="fa fa-google-plus"></i><span class="click-number">14</span></a>
      <a class="btn btn-social btn-social-circle social-dribbble" href="http://dribbble.com/KL-Webmedia"><i class="fa fa-dribbble"></i><span class="click-number">8</span></a>
      <i class="fa fa-circle fa-lg"></i><i class="fa fa-circle fa-2x"></i><i class="fa fa-circle fa-3x"></i>
      <span class="text"><i class="fa fa-comments text-orange"></i> <b>32</b> people like your tutorials</span>
    </div>
  </section>
</div>

<section class="content content-dark testimonial">
  <div class="container">
    <p class="header text-center text-white">We are <strong>51,031</strong> creative teachers so far</p>
    <div class="tab-content quote">
      <blockquote id="tab-nicole-kidman" class="tab-pane fade">
        <p>“This platform is the best idea to teach young people without loosing any time.”</p>
        <cite>Nicole Kidman <span>(actress)</span></cite>
      </blockquote>
      <blockquote id="tab-leland-orser" class="tab-pane fade active in">
        <p>“Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies.”</p>
        <cite>Leland Orser <span>(actor)</span></cite>
      </blockquote>
      <blockquote id="tab-henry-cavill" class="tab-pane fade">
        <p>“Curabitur et ligula. Ut molestie a, ultricies porta urna.Lorem ipsum dolor sit amet enim. Etiam ullamcorper.”</p>
        <cite>Henry Cavill <span>(actor)</span></cite>
      </blockquote>
      <blockquote id="tab-andres-gertrudix" class="tab-pane fade">
        <p>“Maecenas malesuada elit lectus felis, malesuada ultricies. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor.”</p>
        <cite>Andres Gertrudix <span>(actor)</span></cite>
      </blockquote>
      <blockquote id="tab-justin-biber" class="tab-pane fade">
        <p>“Ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies.”</p>
        <cite>Justin Biber <span>(singer)</span></cite>
      </blockquote>
    </div>
    <a href="plans.htm" class="btn btn-theme btn-green">Start teaching</a>
  </div>
</section>

<section class="content content-light">
  <div class="container">
    <p class="header text-center"><strong>Customize</strong> your tutorials <strong>online base</strong></p>
    <p class="text-center">We believe that analysis of your company and your customers is key in responding effectively to your promotional needs and we will work with you to fully understand your business.</p>
    
    <hr class="invisible">
    
    <div class="row">
      <div class="col-md-6">
        <h3>Keep things simple and clean</h3>
        <ul class="fa-ul list-special">
          <li><i class="fa-li fa fa-2x fa-check text-green"></i>update your tutorials daily, weekly or yearly</li>
          <li><i class="fa-li fa fa-2x fa-check text-green"></i>build your own tutorials database</li>
          <li><i class="fa-li fa fa-2x fa-check text-green"></i>create sections and topics for your tutorials</li>
          <li><i class="fa-li fa fa-2x fa-check text-green"></i>create wounderful landing page designs</li>
          <li><i class="fa-li fa fa-2x fa-check text-green"></i>send your followers updates about you works</li>
        </ul>
      </div>
      <div class="col-md-6">
        <h3>Watch the video and create your site</h3>
        <a class="video-prev video-play-here" href="http://www.youtube.com/v/9QscURRuF0g&amp;autoplay=1" style="height:255px; background-image:url('http://i1.ytimg.com/vi/9QscURRuF0g/maxresdefault.jpg');"><i class="fa fa-play"></i><span class="overlay"></span></a>
      </div>
    </div>
  </div>
</section>

<footer class="main bg-dark-img">

  <section class="widgets">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h4>About us</h4>
        <p>At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur.</p>
      </div>
        <div class="col-md-3 footer-qlink">
          <h4>Quick links</h4>
          <nav>
            <ul>
              <li><a href="plans.htm">Start teaching / learning</a></li>
              <li><a href="categories.htm">Tutorials database</a></li>
              <li><a href="about-us.htm">Meet the team</a></li>
              <li><a href="blog-list.htm">Our blog</a></li>
              <li><a href="contact.html">Contact us</a></li>
            </ul>
          </nav>
        </div>
        <div class="col-md-3 footer-blog">
          <h4>Latest blogpostings</h4>
          <ul class="media-list">
            <li class="media">
              <a class="pull-left" href="blog-post.htm"><img class="media-object img-rounded" src="img/face/14.png" alt="author"></a>
              <div class="media-body">
                <h5 class="media-heading"><a href="blog-post.htm">Stet clita kasd</a></h5>
                <p>Lubergren, no sea...</p>
                <span class="footer"><time datetime="2014-01-09T22:11" class="cute-time" data-timestamp="2014/01/09 22:11:19">last year</time> by admin</span> <!-- attribute "datetime" is optional -->
              </div>
            </li>
            <li class="media">
              <a class="pull-left" href="blog-post.htm"><img class="media-object img-rounded" src="img/face/5.png" alt="author"></a>
              <div class="media-body">
                <h5 class="media-heading"><a href="blog-post.htm">Stet clita kasd</a></h5>
                <p>Takimata sanctus est...</p>
                <span class="footer"><time datetime="2013-12-29T20:12" class="cute-time" data-timestamp="2013/12/29 20:12:38">last year</time> by admin</span> <!-- attribute "datetime" is optional -->
              </div>
            </li>
          </ul>
        </div>
        <div class="col-md-3 footer-social">
          <h4>Follow us on</h4>
          <a class="btn btn-social social-facebook" href="https://www.facebook.com/pages/KL-Webmedia/131260293670757"><i class="fa fa-facebook"></i></a>
          <!--<a class="btn-social social-vimeo" href="https://vimeo.com/"><i class="fa fa-vimeo"></i></a>-->
          <a class="btn btn-social social-youtube" href="http://www.youtube.com/"><i class="fa fa-youtube"></i></a>
          <a class="btn btn-social social-twitter" href="https://twitter.com/KLWebmedia"><i class="fa fa-twitter"></i></a>
          <a class="btn btn-social social-gplus" href="https://plus.google.com/113174627408639682462/posts"><i class="fa fa-google-plus"></i></a>
          <!--<a class="btn-social social-blogger" href="https://www.blogger.com/"><i class="fa fa-facebook"></i></a>-->
          <a class="btn btn-social social-dribbble" href="http://dribbble.com/KL-Webmedia"><i class="fa fa-dribbble"></i></a>
          <!--<a class="btn-social social-deviantart" href="http://kl-webmedia.deviantart.com/"><i class="fa fa-deviantart"></i></a>-->
          <a class="btn btn-social social-linkedin" href="https://www.linkedin.com/"><i class="fa fa-linkedin"></i></a>
          <a class="btn btn-social social-tumblr" href="https://www.tumblr.com/"><i class="fa fa-tumblr"></i></a>
          <!--<a class="btn-social social-flickr" href="http://www.flickr.com/"><i class="fa fa-flickr"></i></a>-->
        </div>
    </div>
  </div>
  </section>

  <section class="copyright">
    <div class="container">
      © Copyright 2014 <b>KL-Webmedia.com</b> &nbsp; | &nbsp; All rights reserved
    </div>
  </section>

</footer>

app/views/news/index.slim
- content_for(:page_title, "Новости")

div.container
  div.row
    div.col-md-10.col-md-offset-1
      div.filter
        - @tags.each do |tag|
          = link_to tag.name, news_index_path(tag: tag.name), class: 'btn btn-theme navbar-btn btn-lightblue'
  hr
  - @news.each do |news|
    div.row
      div.col-md-3
        p.blog-img
          = image_tag news.image, class: 'img-thumbnail'
      div.col-md-9

        article.blog-item
          header
            h2.blog-title.center
              = link_to news_path(news.id) do
                = news.title
            p.blue-box.blog-params.center
              span
                i.fa.fa-calendar
                time datetime="2013-01-12T22:11"
                  = " " + news.updated_at.to_formatted_s(:short) + " "
              span
                i.fa.fa-tags
                - news.tag_list.each do |tag|
                  = link_to " " + tag + " ", news_index_path(tag: tag)
              <span class="text-orange">
                i.fa.fa-comments-o
                  |  23 Comments

          p.blog-description
            = news.desc.html_safe
          p.text-right.blog-link-more
            = link_to 'Подробнее', news_path(news.id), class: 'btn btn-theme btn-orange'

  hr

  div.row.center
    div.col-md-12
      = paginate @news, :theme => 'twitter-bootstrap-3'

app/views/news/show.slim
div.container
  div.row.center
    div.col-md-12
      = @news.tag_list.inspect

  div.row.center
    div.col-md-6.col-md-offset-3
      h2 New comment
      hr
      = simple_form_for :comment, url: {controller: 'news', action: 'comment'}, method: 'post' do |f|
        div.form-group
          = f.input_field :title, class: 'form-control', placeholder: 'Title'
        div.form-group
          = f.input_field :comment, as: :text, class: 'form-control', placeholder: 'Comment'
        div.form-group
          = f.hidden_field :id, value: params[:id]
          - if current_user
            = f.hidden_field :user_id, value: current_user.id
          = f.submit class: 'btn btn-success btn-block btn-lg', value: 'Create comment'

app/views/workers/index.slim
div.container
  p.header.text-center
    strong
      | О нас
  p.text-center
    | Текст, текст, текст, текст, текст, текст, текст, текст, текст, текст, текст, текст, текст, текст, текст, текст, текст, текст, текст, текст, текст, текст, текст, текст, текст, текст

  hr.invisible
  hr.invisible

  div.row.center
    div.col-md-12
      div.panel.panel-info
        div.panel-body
          | Специалисты центра

  div.row.our-team
    div.col-md-4
      div.center-block.our-team-item
        figure
          = image_tag Worker.last.image, class: 'img-rounded'
          figcaption
            = Worker.last.name
            em
              = Worker.last.role

  hr.invisible
  hr.invisible

  div.row.center
    div.col-md-12
      div.panel.panel-info
        div.panel-body
          | Практические психологи

  div.row.our-team
    div.col-md-4
      div.center-block.our-team-item
        figure
          img.img-rounded src="/images/2.png"
          figcaption
            | Джони Волкер
            em
              | Youtubber &amp; Blogger

    div.col-md-4
      div.center-block.our-team-item
        figure
          img.img-rounded src="/images/22.png"
          figcaption
            | Джеймс Грин
            em
              | Webdeveloper

    div.col-md-4
      div.center-block.our-team-item
        figure
          img.img-rounded src="/images/24.png"
          figcaption
            | Джон Коннор
            em
              |Language Trainer

  hr.invisible
  hr.invisible

  div.row.center
    div.col-md-12
      div.panel.panel-info
        div.panel-body
          | Логопеды

  div.row.our-team
    div.col-md-4
      div.center-block.our-team-item
        figure
          img.img-rounded src="/images/2.png"
          figcaption
            | Джони Волкер
            em
              | Youtubber &amp; Blogger

    div.col-md-4
      div.center-block.our-team-item
        figure
          img.img-rounded src="/images/22.png"
          figcaption
            | Джеймс Грин
            em
              | Webdeveloper

    div.col-md-4
      div.center-block.our-team-item
        figure
          img.img-rounded src="/images/24.png"
          figcaption
            | Джон Коннор
            em
              |Language Trainer

  hr.invisible
  hr.invisible

  div.row.center
    div.col-md-12
      div.panel.panel-info
        div.panel-body
          | Социальные педагоги

  div.row.our-team
    div.col-md-4
      div.center-block.our-team-item
        figure
          img.img-rounded src="/images/2.png"
          figcaption
            | Джони Волкер
            em
              | Youtubber &amp; Blogger

    div.col-md-4
      div.center-block.our-team-item
        figure
          img.img-rounded src="/images/22.png"
          figcaption
            | Джеймс Грин
            em
              | Webdeveloper

    div.col-md-4
      div.center-block.our-team-item
        figure
          img.img-rounded src="/images/24.png"
          figcaption
            | Джон Коннор
            em
              |Language Trainer

  hr.invisible
  hr.invisible