config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root 'main#index'

  resources :news
  resources :articles
  resources :workers
  resources :services

  post 'comment', to: 'news#comment'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user && user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :dashboard              # grant access to the dashboard
      can :manage, :all
    end

  end
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  desc       :text
#  image      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Article < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  acts_as_taggable
end

app/models/ckeditor/asset.rb
# == Schema Information
#
# Table name: ckeditor_assets
#
#  id                :integer          not null, primary key
#  data_file_name    :string(255)      not null
#  data_content_type :string(255)
#  data_file_size    :integer
#  assetable_id      :integer
#  assetable_type    :string(30)
#  type              :string(30)
#  width             :integer
#  height            :integer
#  created_at        :datetime
#  updated_at        :datetime
#

class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/picture.rb
# == Schema Information
#
# Table name: ckeditor_assets
#
#  id                :integer          not null, primary key
#  data_file_name    :string(255)      not null
#  data_content_type :string(255)
#  data_file_size    :integer
#  assetable_id      :integer
#  assetable_type    :string(30)
#  type              :string(30)
#  width             :integer
#  height            :integer
#  created_at        :datetime
#  updated_at        :datetime
#

class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  title            :string(50)       default("")
#  comment          :text
#  commentable_id   :integer
#  commentable_type :string(255)
#  user_id          :integer
#  role             :string(255)      default("comments")
#  created_at       :datetime
#  updated_at       :datetime
#

class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment
  validates :comment, presence: :true

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/news.rb
class News < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  acts_as_taggable
  acts_as_commentable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  before_create do

    # Проверка на наличие пользователей.
    # Если ты первый, то удача повернулась к тебе лицом и ты становишься админом!! Та-да!!
      if User.first.nil?
        self.admin = 1
      end

  end

end

app/models/worker.rb
# == Schema Information
#
# Table name: workers
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  role       :string(255)
#  image      :string(255)
#  desc       :text
#  created_at :datetime
#  updated_at :datetime
#

class Worker < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

# Проверка на контроллер, если devise, то вызывает метод configure_permitted_parameters для настройки разрешенных параметров
  before_filter :configure_permitted_parameters, if: :devise_controller?
    
protected

# Параметры, которые принимает гем Devise через пользовательские формы на сайте
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:sign_up) << :email
    devise_parameter_sanitizer.for(:sign_in) << :username
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    if params[:tag]
      @articles = Article.tagged_with(params[:tag]).page(params[:page]).per(3)
    else
      @articles = Article.all.page(params[:page]).per(3)
    end
    @tags = Article.tag_counts
  end

  def show
    @article = Article.find(params[:id])
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
  end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  def index
    if params[:tag]
      @news = News.tagged_with(params[:tag]).page(params[:page]).per(3)
    else
      @news = News.all.page(params[:page]).per(3)
    end
    @tags = News.tag_counts
  end

  def show
    @news = News.find(params[:id])
  end

  def comment
    commentable = News.find(params[:comment][:id])
    comment = commentable.comments.create
    comment.title = params[:comment][:title]
    comment.comment = params[:comment][:comment]
    comment.user_id = params[:comment][:user_id]
    comment.save
    redirect_to :back
  end

  private

    def comment_params
      params.require(:comment).require(:title, :comment)
    end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def index

  end

  def show
    @service = Service.find(params[:id])
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController

  def index
    @workers = Worker.all
  end

  def show
    @worker  = Worker.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/layouts/application.html.erb
/ encoding: utf-8
doctype html
html
  head
    title
      = page_title(app_name: "", separator: "")

    link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  
  body
    = yield

    script src="/assets/js/jquery-1.10.2.min.js"
    script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"
    script src="/assets/js/animate.js"
    script src="/assets/js/jquery.cuteTime.min.js"
    script src="/assets/js/script.js"
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/layouts/application.slim
/ encoding: utf-8
doctype html
html
  head
    title
      = page_title(app_name: "", separator: "")

    link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    = render './partials/header'
    = yield
    = render './partials/footer'
    script src="/assets/js/jquery-1.10.2.min.js"
    script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"
    script src="/assets/js/animate.js"
    script src="/assets/js/jquery.cuteTime.min.js"
    script src="/assets/js/script.js"
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/partials/_footer.slim
footer.main.footer-dark-img
  section.widgets
    div.container
      div.row.center
        | © 2015 Горловский городской центр психологической службы

app/views/partials/_header.html.erb
<header class="main bg-dark-img home-1">
  <div class="container">
    <nav class="navbar" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.htm"><img id="logo" src="img/logo.png" alt="eLearn"></a>
      </div>
      <div class="collapse navbar-collapse">
      <div class="navbar-right menu-main"> 
        <ul class="nav navbar-nav">
          <li class="dropdown active">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span>Home</span> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="index.htm">Home, version 1</a></li>
              <li><a href="index2.htm">Home, version 2</a></li>
              <li><a href="index3.htm">Home, version 3</a></li>
            </ul>
          </li>
          <li><a href="about-us.htm"><span>About us</span></a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span>Video</span> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="categories.htm">Categories of video</a></li>
              <li><a href="videos-list.htm">Video list</a></li>
              <li><a href="videos-grid.htm">Video list (grid)</a></li>
              <li><a href="video.htm">Video film detail</a></li>
            </ul>
          </li>
          <li><a href="features.htm"><span>Features</span></a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span>Blog</span> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="blog-list.htm">Blog list</a></li>
              <li><a href="blog-post.htm">Blog post detail</a></li>
            </ul>
          </li>
          <li><a href="contact.htm"><span>Contact us</span></a></li>
        </ul>
        <a class="btn btn-theme navbar-btn btn-default sign-in" href="#">Sign in</a>
        <a class="btn btn-theme navbar-btn btn-orange  sign-up" href="register.htm">Sign up</a>
      </div>
      </div>
    </nav>
    
    <p class="header text-center text-white"><strong>Learning</strong> made easy via the <strong>internet</strong> <a href="plans.htm" class="btn btn-theme btn-orange">Start today</a></p>
    
    <!-- Screens -->
    <div class="screens animation-domready">
      <p style="height: 470px;">
        <img src="img/home1_tab1.png" data-animation-delay="2.5s" data-animation="fadeInUp" class="img-responsive animated fadeInUp" alt="" style="-webkit-animation-delay: 0.5s; opacity: 0; left: 15% !important; ">
      </p>
    </div>
  </div>
</header>

app/views/partials/_header.slim
header.main.bg-dark-img.home-1
  div.container
    nav.navbar role="navigation"

      div.navbar-header
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-collapse"
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        = link_to root_path, class: 'navbar-brand' do
          img id="logo" src="/images/logo.png" alt=""

      div.collapse.navbar-collapse
        div.navbar-right.menu-main
          ul.nav.navbar-nav
            li
              = link_to 'Новости', news_index_path
            li
              = link_to 'Статьи', articles_path
            li
              = link_to 'Услуги', services_path
            li
              = link_to 'О нас', workers_path
          / a.btn.btn-theme.navbar-btn.btn-default.sign-in href="#"
            | Sign in
          / a.btn.btn-theme.navbar-btn.btn-orange.sign-up href="register.htm"
            | Sign up
    hr
    div.screens.animation-domready
      img.img-responsive.animated.fadeInUp src="/images/main.jpg" data-animation-delay="1s" data-animation="fadeInUp" alt="" style="-webkit-animation-delay: 2.5s; opacity: 0;"